name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: test-env
        python-version: "3.10"

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        # Remove tmp files
        sudo rm -rf /tmp/*

        # Install conda packages
        conda env list
        conda info
        conda config --add channels defaults
        conda config --add channels bioconda
        conda config --add channels conda-forge
        conda install pandas==2.2.2
        conda install maturin
        conda install rust
        conda install pylint
        conda install coveralls
        conda install pytest
        conda install pytest-cov
        conda install pysam==0.22.0
        conda install numpy==1.26.2
        conda install r-base==4.4.1
        Rscript -e 'install.packages("dplyr", repos="https://cloud.r-project.org/")'
        Rscript -e 'install.packages("ggplot2", repos="https://cloud.r-project.org/")'
        Rscript -e 'install.packages("optparse", repos="https://cloud.r-project.org/")'
        pip install pyensembl
  
        # Install vstol
        pip install . --verbose

    - name: Download ensembl data
      shell: bash -l {0}
      run: |
        pyensembl install --release 95 --species human

    - name: Run linter
      shell: bash -l {0}
      run: |
        chmod +x lint.sh
        bash lint.sh

    - name: Run unit tests
      shell: bash -l {0}
      run: |
        chmod +x unittest.sh
        bash unittest.sh